# android-8.1.yaml
#
# Crowdin configuration file for OmniROM
#
# Copyright (C) 2017 OmniROM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api_token_env: "OMNI_CROWDIN_ACCESS_TOKEN"
base_path_env: "OMNI_CROWDIN_BASE_PATH"
base_path_contains_branch_subfolders: false
project_id_env: "OMNI_CROWDIN_PROJECT_ID"
preserve_hierarchy: true

files:
# Frameworks

# framework-res
  -
    source:      '/frameworks/base/core/res/res/values/custom_strings.xml'
    translation: '/frameworks/base/core/res/res/values-%android_code%/%original_file_name%'
    languages_mapping: &anchor
      android_code:
        af: af
        am: am
        ar: ar
        az: az-rAZ
        be: be
        bg: bg
        ca: ca
        cs: cs
        da: da
        de: de
        el: el
        es-ES: es
        et: et
        fa: fa
        fi: fi
        fr: fr
        he: iw
        hi: hi
        hr: hr
        hu: hu
        hy-AM: hy
        id: in
        it: it
        ja: ja
        ka: ka
        km: km
        ko: ko
        lo: lo-rLA
        lt: lt
        lv: lv
        mn: mn
        ms: ms
        nb: nb
        ne-NP: ne
        nl: nl
        pl: pl
        pt-PT: pt-rPT
        pt-BR: pt-rBR
        rm-CH: rm
        ro: ro
        ru: ru
        si-LK: si
        sk: sk
        sl: sl
        sr: sr
        sv-SE: sv
        sw: sw
        th: th
        tl: tl
        tr: tr
        uk: uk
        vi: vi
        zh-CN: zh-rCN
        zh-HK: zh-rHK
        zh-TW: zh-rTW
        zu: zu

# SystemUI
  -
    source:      '/frameworks/base/packages/SystemUI/res/values/custom_strings.xml'
    translation: '/frameworks/base/packages/SystemUI/res/values-%android_code%/%original_file_name%'
    languages_mapping: *anchor


# Packages

# OmniGears
  -
    source:      '/packages/apps/OmniGears/res/values/custom_strings.xml'
    translation: '/packages/apps/OmniGears/res/values-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# OmniJaws
  -
    source:      '/packages/services/OmniJaws/res/values/strings.xml'
    translation: '/packages/services/OmniJaws/res/values-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# OmniStyle
  -
    source:      '/packages/apps/OmniStyle/res/values/strings.xml'
    translation: '/packages/apps/OmniStyle/res/values-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# OmniSwitch
  -
    source:      '/packages/apps/OmniSwitch/res/values/strings.xml'
    translation: '/packages/apps/OmniSwitch/res/values-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# OpenDelta
  -
    source:      '/packages/apps/OpenDelta/res/values/strings.xml'
    translation: '/packages/apps/OpenDelta/res/values-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# Settings
  -
    source:      '/packages/apps/Settings/res/values/custom_strings.xml'
    translation: '/packages/apps/Settings/res/values-%android_code%/%original_file_name%'
    languages_mapping: *anchor


# Launcher3
  -
    source:      '/packages/apps/Launcher3/res/values/custom_strings.xml'
    translation: '/packages/apps/Launcher3/res/values-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# Dialer
  -
    source:      '/packages/apps/Dialer/java/com/android/dialer/app/res/values/custom_strings.xml'
    translation: '/packages/apps/Dialer/java/com/android/dialer/app/res/values-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# Telephony
#  -
#    source:      '/packages/services/Telephony/res/values/custom_strings.xml'
#    translation: '/packages/services/Telephony/res/values-%android_code%/%original_file_name%'
#    languages_mapping: *anchor

# OmniChange
  -
    source:      '/packages/apps/OmniChange/app/src/main/res/values/strings.xml'
    translation: '/packages/apps/OmniChange/app/src/main/res/values-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  -
    source:      '/packages/apps/OmniLib/res/values/strings.xml'
    translation: '/packages/apps/OmniLib/res/values-%android_code%/%original_file_name%'
    languages_mapping: *anchor

#  -
#    source:      '/packages/providers/DownloadProvider/res/values/omni_*.xml'
#    translation: '/packages/providers/DownloadProvider/res/values-%android_code%/%original_file_name%'
#    languages_mapping: *anchor

  -
    source:      '/packages/apps/Messaging/res/values/custom_strings.xml'
    translation: '/packages/apps/Messaging/res/values-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  -
    source:      '/packages/apps/OmniRemote/app/src/main/res/values/strings.xml'
    translation: '/packages/apps/OmniRemote/app/src/main/res/values-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  -
    source:      '/packages/apps/ThemePicker/res/values/custom_strings.xml'
    translation: '/packages/apps/ThemePicker/res/values-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  -
    source:      '/packages/apps/Matlog/app/src/main/res/values/strings.xml'
    translation: '/packages/apps/Matlog/app/src/main/res/values-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  -
    source:      '/packages/apps/OmniStore/app/src/main/res/values/strings.xml'
    translation: '/packages/apps/OmniStore/app/src/main/res/values-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  -
    source:      '/packages/apps/OmniStoreInstaller/app/src/main/res/values/strings.xml'
    translation: '/packages/apps/OmniStoreInstaller/app/src/main/res/values-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  -
    source:      '/packages/apps/Gallery2/res/values/custom_strings.xml'
    translation: '/packages/apps/Gallery2/res/values-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  -
    source:      '/packages/apps/Calendar/res/values/custom_strings.xml'
    translation: '/packages/apps/Calendar/res/values-%android_code%/%original_file_name%'
    languages_mapping: *anchor

#  -
#    source:      '/packages/apps/ExactCalculator/res/values/custom_strings.xml'
#    translation: '/packages/apps/ExactCalculator/res/values-%android_code%/%original_file_name%'
#    languages_mapping: *anchor

  -
    source:      '/packages/apps/Phonograph/app/src/main/res/values/custom_strings.xml'
    translation: '/packages/apps/Phonograph/app/src/main/res/values-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  -
    source:      '/packages/apps/Phonograph/app/src/main/res/values/strings.xml'
    translation: '/packages/apps/Phonograph/app/src/main/res/values-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# devices
#  -
#    source:      '/device/oneplus/oneplus6/DeviceParts/res/values/strings.xml'
#    translation: '/device/oneplus/oneplus6/DeviceParts/res/values-%android_code%/%original_file_name%'
#    languages_mapping: *anchor
    
  -
    source:      '/device/oneplus/oneplus7pro/DeviceParts/res/values/strings.xml'
    translation: '/device/oneplus/oneplus7pro/DeviceParts/res/values-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  -
    source:      '/device/asus/zenfone6/DeviceParts/res/values/strings.xml'
    translation: '/device/asus/zenfone6/DeviceParts/res/values-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  -
    source:      '/device/brcm/rpi4/DeviceParts/res/values/strings.xml'
    translation: '/device/brcm/rpi4/DeviceParts/res/values-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  -
    source:      '/device/asus/rog2/DeviceParts/res/values/strings.xml'
    translation: '/device/asus/rog2/DeviceParts/res/values-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  -
    source:      '/device/asus/sm8250-common/DeviceParts/res/values/strings.xml'
    translation: '/device/asus/sm8250-common/DeviceParts/res/values-%android_code%/%original_file_name%'
    languages_mapping: *anchor